version: 2

models:
  - name: fct_weather
    description: >
      Fact table (fct_weather) that incrementally loads cleaned and 
      standardized weather data from the intermediate model (int_weather). 
      It ensures efficient data processing by inserting only new records based on the date and 
      automatically adapting to schema changes. Serving as the final, analytics-ready repository, 
      this fact table consolidates deduplicated weather data for downstream reporting and analysis.
    columns:
      - name: DATE
        description: "Date of the weather data (converted from last updated timestamp)"
      - name: COUNTRY
        description: "Name of the country"
      - name: TEMPERATURE
        description: "Temperature in Celsius"
      - name: WEATHER_CONDITION
        description: "Description of the weather condition"
      - name: WIND_SPEED
        description: "Wind speed in kilometers per hour"
      - name: WIND_DIRECTION
        description: "Wind direction as text"
      - name: PRESSURE
        description: "Atmospheric pressure in millibars"
      - name: PRECIPITATION
        description: "Precipitation in millimeters"
      - name: HUMIDITY
        description: "Humidity percentage"
      - name: CLOUD_COVER
        description: "Cloud cover percentage"
      - name: FEELS_LIKE
        description: "Feels-like temperature in Celsius"
      - name: VISIBILITY
        description: "Visibility in kilometers"
      - name: UV
        description: "UV index"
      - name: GUST
        description: "Wind gust speed in kilometers per hour"
      - name: AQ_CO
        description: "Air quality: Carbon Monoxide (CO)"
      - name: AQ_OZONE
        description: "Air quality: Ozone (O3)"
      - name: AQ_NO2
        description: "Air quality: Nitrogen Dioxide (NO2)"
      - name: AQ_SO2
        description: "Air quality: Sulphur Dioxide (SO2)"
      - name: AQ_PM2_5
        description: "Air quality: Particulate Matter 2.5 (PM2.5)"
      - name: AQ_PM10
        description: "Air quality: Particulate Matter 10 (PM10)"
      - name: AQ_US_EPA_INDEX
        description: "Air quality index (US EPA)"
      - name: AQ_GB_DEFRA_INDEX
        description: "Air quality index (GB DEFRA)"
      - name: SUNRISE_TIME
        description: "Time of sunrise"
      - name: SUNSET_TIME
        description: "Time of sunset"
      - name: MOONRISE_TIME
        description: "Time of moonrise"
      - name: MOONSET_TIME
        description: "Time of moonset"
      - name: MOON_PHASE
        description: "Phase of the moon"
      - name: MOON_ILLUMINATION
        description: "Percentage of moon illumination"
  - name: fct_mon_avg_weather
    description: >
      model materializes a finalized, structured table of monthly average weather and air quality metrics by country and city. 
      It selects cleaned and rounded data from the eph_mon_avg_rnd_weather model, 
      making it ready for consumption in dashboards, analytics, and business reporting, 
      with optimized structure for fast querying and presentation.
    columns:
    - name: country
      description: "Name of the country where the weather data was recorded."
    - name: city
      description: "Name of the city where the weather data was recorded."
    - name: month
      description: "Name of the month (e.g., January, February) extracted from the weather record date."
    - name: temperature
      description: "Average temperature (°C) for the month in the specified city and country."
    - name: pressure
      description: "Average atmospheric pressure (millibars) for the month in the specified city and country."
    - name: visibility
      description: "Average visibility (kilometers) for the month in the specified city and country."
    - name: wind_speed
      description: "Average wind speed (km/h) for the month in the specified city and country."
    - name: precipitation
      description: "Average precipitation (millimeters) for the month in the specified city and country."
    - name: humidity
      description: "Average humidity percentage for the month in the specified city and country."
    - name: feels_like
      description: "Average 'feels like' temperature (°C) for the month in the specified city and country."
    - name: cloud_cover
      description: "Average cloud cover percentage for the month in the specified city and country."
    - name: moon_illumination
      description: "Average moon illumination percentage for the month in the specified city and country."
    - name: uv
      description: "Average UV index for the month in the specified city and country."
    - name: gust
      description: "Average wind gust speed (km/h) for the month in the specified city and country."
    - name: aq_ozone
      description: "Average ozone (O₃) air quality reading for the month in the specified city and country."
    - name: aq_us_epa_index
      description: "Average US EPA air quality index for the month in the specified city and country."
    - name: aq_no2
      description: "Average nitrogen dioxide (NO₂) air quality reading for the month in the specified city and country."
    - name: aq_pm2_5
      description: "Average PM2.5 (fine particulate matter) concentration for the month in the specified city and country."
    - name: aq_gb_defra_index
      description: "Average GB DEFRA air quality index for the month in the specified city and country."
    - name: aq_pm10
      description: "Average PM10 (coarse particulate matter) concentration for the month in the specified city and country."
    - name: aq_so2
      description: "Average sulfur dioxide (SO₂) air quality reading for the month in the specified city and country."
    - name: aq_co
      description: "Average carbon monoxide (CO) air quality reading for the month in the specified city and country."