SELECT
    CAST(last_updated AS DATE) AS DATE,
    country AS COUNTRY,
    temperature_celsius AS TEMPERATURE,
    condition_text AS WEATHER_CONDITION,
    wind_kph AS WIND_KPH,
    wind_direction AS WIND_DIRECTION,
    pressure_mb AS PRESSURE_MB,
    precip_mm AS PRECIP_MM,
    humidity AS HUMIDITY,
    cloud AS CLOUD_COVER,
    feels_like_celsius AS FEELS_LIKE,
    visibility_km AS VISIBILITY_KM,
    uv_index AS UV_INDEX,
    gust_kph AS GUST_KPH,
    air_quality_carbon_monoxide AS AQ_CO,
    air_quality_ozone AS AQ_OZONE,
    air_quality_nitrogen_dioxide AS AQ_NO2,
    air_quality_sulphur_dioxide AS AQ_SO2,
    air_quality_pm2_5 AS AQ_PM2_5,
    air_quality_pm10 AS AQ_PM10,
    air_quality_us_epa_index AS AQ_US_EPA_INDEX,
    air_quality_gb_defra_index AS AQ_GB_DEFRA_INDEX,
    sunrise AS SUNRISE_TIME,
    sunset AS SUNSET_TIME,
    moonrise AS MOONRISE_TIME,
    moonset AS MOONSET_TIME,
    moon_phase AS MOON_PHASE,
    moon_illumination AS MOON_ILLUMINATION
FROM {{ source('kaggle_datasets', 'weather_dataset_raw') }}