version: 2

models:
  - name: eph_mon_avg_weather
    description: >
      Monthly average of weather and air quality data by country and city. 
      It extracts the month from each record’s date and calculates the average values of key weather metrics (such as temperature, wind speed, 
      humidity, and precipitation) and air quality indicators (like AQI components) using window functions. 
      The result provides a summarized dataset that supports trend analysis, 
      reporting, and higher-level insights across different regions over time.
    columns:
    - name: country
      description: "Name of the country where the weather data was recorded."
    - name: city
      description: "Name of the city where the weather data was recorded."
    - name: month
      description: "Name of the month (e.g., January, February) extracted from the weather record date."
    - name: temperature
      description: "Average temperature (°C) for the month in the specified city and country."
    - name: pressure
      description: "Average atmospheric pressure (millibars) for the month in the specified city and country."
    - name: visibility
      description: "Average visibility (kilometers) for the month in the specified city and country."
    - name: wind_speed
      description: "Average wind speed (km/h) for the month in the specified city and country."
    - name: precipitation
      description: "Average precipitation (millimeters) for the month in the specified city and country."
    - name: humidity
      description: "Average humidity percentage for the month in the specified city and country."
    - name: feels_like
      description: "Average 'feels like' temperature (°C) for the month in the specified city and country."
    - name: cloud_cover
      description: "Average cloud cover percentage for the month in the specified city and country."
    - name: moon_illumination
      description: "Average moon illumination percentage for the month in the specified city and country."
    - name: uv
      description: "Average UV index for the month in the specified city and country."
    - name: gust
      description: "Average wind gust speed (km/h) for the month in the specified city and country."
    - name: aq_ozone
      description: "Average ozone (O₃) air quality reading for the month in the specified city and country."
    - name: aq_us_epa_index
      description: "Average US EPA air quality index for the month in the specified city and country."
    - name: aq_no2
      description: "Average nitrogen dioxide (NO₂) air quality reading for the month in the specified city and country."
    - name: aq_pm2_5
      description: "Average PM2.5 (fine particulate matter) concentration for the month in the specified city and country."
    - name: aq_gb_defra_index
      description: "Average GB DEFRA air quality index for the month in the specified city and country."
    - name: aq_pm10
      description: "Average PM10 (coarse particulate matter) concentration for the month in the specified city and country."
    - name: aq_so2
      description: "Average sulfur dioxide (SO₂) air quality reading for the month in the specified city and country."
    - name: aq_co
      description: "Average carbon monoxide (CO) air quality reading for the month in the specified city and country."

  - name: eph_mon_avg_rnd_weather
    description: >
      Monthly average weather and air quality data by rounding all n
      umeric metrics to two decimal places for consistency and readability. 
      It selects key weather and environmental indicators for each country, 
      city, and month from the eph_mon_avg_weather model, preparing a clean, 
      presentation-ready dataset for reporting, dashboards, or further analysis
    columns:
    - name: country
      description: "Name of the country where the weather data was recorded."
    - name: city
      description: "Name of the city where the weather data was recorded."
    - name: month
      description: "Name of the month (e.g., January, February) extracted from the weather record date."
    - name: temperature
      description: "Average temperature (°C) for the month in the specified city and country."
    - name: pressure
      description: "Average atmospheric pressure (millibars) for the month in the specified city and country."
    - name: visibility
      description: "Average visibility (kilometers) for the month in the specified city and country."
    - name: wind_speed
      description: "Average wind speed (km/h) for the month in the specified city and country."
    - name: precipitation
      description: "Average precipitation (millimeters) for the month in the specified city and country."
    - name: humidity
      description: "Average humidity percentage for the month in the specified city and country."
    - name: feels_like
      description: "Average 'feels like' temperature (°C) for the month in the specified city and country."
    - name: cloud_cover
      description: "Average cloud cover percentage for the month in the specified city and country."
    - name: moon_illumination
      description: "Average moon illumination percentage for the month in the specified city and country."
    - name: uv
      description: "Average UV index for the month in the specified city and country."
    - name: gust
      description: "Average wind gust speed (km/h) for the month in the specified city and country."
    - name: aq_ozone
      description: "Average ozone (O₃) air quality reading for the month in the specified city and country."
    - name: aq_us_epa_index
      description: "Average US EPA air quality index for the month in the specified city and country."
    - name: aq_no2
      description: "Average nitrogen dioxide (NO₂) air quality reading for the month in the specified city and country."
    - name: aq_pm2_5
      description: "Average PM2.5 (fine particulate matter) concentration for the month in the specified city and country."
    - name: aq_gb_defra_index
      description: "Average GB DEFRA air quality index for the month in the specified city and country."
    - name: aq_pm10
      description: "Average PM10 (coarse particulate matter) concentration for the month in the specified city and country."
    - name: aq_so2
      description: "Average sulfur dioxide (SO₂) air quality reading for the month in the specified city and country."
    - name: aq_co
      description: "Average carbon monoxide (CO) air quality reading for the month in the specified city and country."